api/urls.py
from django.conf.urls import patterns, include, url 
from rest_framework.urlpatterns import format_suffix_patterns 
from . import views



urlpatterns = patterns('api.views',
 	url(r'getflag', views.getflag),
 	url(r'getfechahora', views.getfechahora),
 	url(r'getpasswordqorder', views.getpasswordqorder),
 	url(r'getcodigosiddesc', views.getcodigosiddesc),
 	url(r'getdata', views.getdata),
   )

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from core.views import log_in, log_out, index,foto


admin.site.site_url = '/qorderweb/'
urlpatterns = [
    url(r'^qorderweb/admin/login/$', log_in, name='login_main'),
    url(r'^qorderweb/admin/logout/$', log_out, name='logout_main'),
    url(r'^qorderweb/admin/', include(admin.site.urls), name='admin'),
    url(r'^qorderweb/login$', log_in, name='login'),
    url(r'^qorderweb/logout$', log_out, name='logout'),
    url(r'^qorderweb/$', index, name='index'),
    url(r'^qorderweb/qorder/', include('qorder.urls', namespace='qorder')),
    url(r'^qorderweb/api/', include('api.urls')),
    url(r'^qorderweb/foto/$', foto, name='foto'),
    

    
]

def handler500(request): 
    response = render_to_response('500.html', {}, context_instance=RequestContext(request)) 
    response.status_code = 500 
    return response


admin.site.site_header = settings.TITLE_SITE
admin.site.site_title = 'settings.TITLE_SITE'

qorder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from qorder.views import orderListJson, suminListJson

from django.contrib.auth.decorators import login_required


from . import views


urlpatterns = [

    url(r'^user/password/$', views.change_password, name='change_password'),
    url(r'^user/about/$', views.about, name='about'),

    # GESTION TERMINALES PORTATILES
    url(r'^qoadmin/tp/gestion/$', views.atp_main, name='atp_main'),
    url(r'^qoadmin/tp/edit_tp/$', views.atp_edit, name='atp_edit'),
    url(r'^qoadmin/tp/edit1_tp/$', views.atp_edit1, name='atp_edit1'),
    url(r'^qoadmin/tp/cflags/$', views.tp_cflags, name='tp_cflags'),

    # SEMANA DE TRABAJO
    url(r'^semana/$', views.semana, name='semana'),
    url(r'^semana_save/$', views.semana_save, name='semana_save'),
    # GESTION TECNICOS
    url(r'^qoadmin/tecnicos/gestion/$', views.tecnicos_main, name='tecnicos_main'),
    url(r'^qoadmin/tecnicos/gt_tabla$', views.gt_tabla, name='gt_tabla'),
    url(r'^qoadmin/tecnicos/save/$', views.tecnico_save, name='tecnico_save'),
    url(r'^qoadmin/tecnicos/new/$', views.tecnico_new, name='tecnico_new'),
    url(r'^qoadmin/tecnicos/edit/$', views.tecnico_edit, name='tecnico_edit'),
    url(r'^qoadmin/tecnicos/cflags/$', views.tecnico_cflag, name='tecnico_cflags'),
    url(r'^qoadmin/tecnicos/tecnico/$',
        views.tecnico_liberarTPL, name='tecnico_liberarTPL'),

    # GESTION ANOMALIAS
    url(r'^qoadmin/anomalias/gestion/$',
        views.anomalias_main, name='anomalias_main'),
    url(r'^qoadmin/anomalias/gt_tabla$',
        views.anomalias_tabla, name='anomalias_tabla'),
    url(r'^qoadmin/anomalias/save/$', views.anomalias_save, name='anomalias_save'),
    url(r'^qoadmin/anomalias/edit/$', views.anomalias_edit, name='anomalias_edit'),
    url(r'^qoadmin/anomalias/new/$', views.anomalias_new, name='anomalias_new'),
    url(r'^qoadmin/anomalias/cflags/$',
        views.anomalias_cflags, name='anomalias_cflags'),
    url(r'^qoadmin/anomalias/anomalias_obs/$',
        views.anomalias_obs, name='anomalias_obs'),
    url(r'^qoadmin/anomalias/agregarobservaciones/$',
        views.agregarobservaciones, name='agregarobservaciones'),



    # GESTION CODIGOS
    url(r'^qoadmin/codigos/gestion/$', views.codigos_main, name='codigos_main'),
    url(r'^qoadmin/codigos/gt_tabla$', views.codigos_tabla, name='codigos_tabla'),
    url(r'^qoadmin/codigos/save/$', views.codigos_save, name='codigos_save'),
    url(r'^qoadmin/codigos/edit/$', views.codigos_edit, name='codigos_edit'),
    url(r'^qoadmin/codigos/new/$', views.codigos_new, name='codigos_new'),
    url(r'^qoadmin/codigos/cflags/$', views.codigos_cflags, name='codigos_cflags'),

    # GESTION ENCUESTAS
    url(r'^qoadmin/encuestas/gestion/$',
        views.encuestas_main, name='encuestas_main'),
    url(r'^qoadmin/encuestas/save/$', views.encuestas_save, name='encuestas_save'),
    url(r'^qoadmin/encuestas/edit/$', views.encuestas_edit, name='encuestas_edit'),
    url(r'^qoadmin/encuestas/new/$', views.encuestas_new, name='encuestas_new'),
    url(r'^qoadmin/encuestas/cflags/$',
        views.encuestas_cflags, name='encuestas_cflags'),
    url(r'^qoadmin/encuestas/detail/$',
        views.encuesta_detail, name='encuesta_detail'),
    url(r'^qoadmin/encuestas/newpregunta/$',
        views.pregunta_new, name='pregunta_new'),
    url(r'^qoadmin/encuestas/savepregunta/$',
        views.pregunta_save, name='pregunta_save'),
    url(r'^qoadmin/encuestas/editpregunta/$',
        views.pregunta_edit, name='pregunta_edit'),
    url(r'^qoadmin/encuestas/ordenpregunta/$',
        views.pregunta_orden, name='pregunta_orden'),
    # GESTION PROBLEMAS
    url(r'^qoadmin/problemas/gestion/$',
        views.problemas_main, name='problemas_main'),
    url(r'^qoadmin/problemas/gt_tabla$',
        views.problemas_tabla, name='problemas_tabla'),
    url(r'^qoadmin/problemas/save/$', views.problemas_save, name='problemas_save'),
    url(r'^qoadmin/problemas/edit/$', views.problemas_edit, name='problemas_edit'),
    url(r'^qoadmin/problemas/new/$', views.problemas_new, name='problemas_new'),
    url(r'^qoadmin/problemas/cflags/$',
        views.problemas_cflags, name='problemas_cflags'),


    # GESTION TIPOS ORDENES
    url(r'^qoadmin/tiposordenes/gestion/$',
        views.tiposordenes_main, name='tiposordenes_main'),
    url(r'^qoadmin/tiposordenes/gt_tabla$',
        views.tiposordenes_tabla, name='tiposordenes_tabla'),
    url(r'^qoadmin/tiposordenes/propiedades$',
        views.tiposordenes_propiedades, name='tiposordenes_propiedades'),
    url(r'^qoadmin/tiposordenes/anomaliaxtipo_save$',
        views.tiposordenes_anomaliaxtipo_save, name='tiposordenes_anomaliaxtipo_save'),
    url(r'^qoadmin/tiposordenes/anomaliaxtipo_cflags$',
        views.anomaliaxtipo_cflags, name='anomaliaxtipo_cflags'),

    # GESTION RUTA_SUM
    url(r'^qoadmin/rutasum/gestion/$', views.rutasum_main, name='rutasum_main'),
    url(r'^qoadmin/rutasum/rutasum_tabla$',
        views.rutasum_tabla, name='rutasum_tabla'),
    url(r'^qoadmin/rutasum/rutasum_edit$',
        views.rutasum_edit, name='rutasum_edit'),
    url(r'^qoadmin/rutasum/rutasum_new$', views.rutasum_new, name='rutasum_new'),
    url(r'^qoadmin/rutasum/rutasum_save$',
        views.rutasum_save, name='rutasum_save'),
    url(r'^qoadmin/rutasum/suministro_tabla$',
        views.suministro_tabla, name='suministro_tabla'),
    url(r'^qoadmin/rutasum/tabla_suministros_sin_ruta$',
        views.tabla_suministros_sin_ruta, name='tabla_suministros_sin_ruta'),
    url(r'^qoadmin/rutasum/trasferir_suministro$',
        views.trasferir_suministro, name='trasferir_suministro'),
    url(r'^qoadmin/rutasum/rutasum_delete$',
        views.rutasum_delete, name='rutasum_delete'),
    url(r'^qoadmin/rutasum/suministro_delete$',
        views.suministro_delete, name='suministro_delete'),

    # GENERACION
    url(r'^qoordenes/generacion/main/$',
        views.generacion_main, name='generacion_main'),
    url(r'^qoordenes/generacion/generacion_ruta/$',
        views.generacion_ruta, name='generacion_ruta'),
    url(r'^qoordenes/generacion/generar/$', views.generar, name='generar'),



    # ASIGNACION
    url(r'^qoordenes/asignacion/main/$',
        views.asignacion_main, name='asignacion_main'),
    url(r'^qoordenes/asignacion/attable/$',
        views.asignacion_tech, name='asignacion_tech'),
    url(r'^qoordenes/asignacion/artable/$',
        views.asignacion_route, name='asignacion_route'),
    url(r'^qoordenes/asignacion/asignar_route/$',
        views.asignar_route, name='asignar_route'),
    url(r'^qoordenes/asignacion/asignar_asign/$',
        views.asignacion_asignaciones, name='asignacion_asignaciones'),
    url(r'^qoordenes/asignacion/asignar_desasign/$',
        views.asignacion_desasignar, name='asignacion_desasignar'),
    url(r'^qoordenes/asignacion/guardar_asignar_ordenes/$',
        views.guardar_asignar_ordenes, name='guardar_asignar_ordenes'),
    


    # SEGMENTACIÓN RUTAS
     url(r'^qoordenes/segmentacion_rutas/main/$',
        views.segmentacion_rutas_main, name='segmentacion_rutas_main'),
     url(r'^qoordenes/segmentacion_rutas/obtener_rutas_segmentos/$',
        views.obtener_rutas_segmentos, name='obtener_rutas_segmentos'),
     url(r'^qoordenes/asignacion/segmento/artable/$',
        views.asignacion_segmento_route, name='asignacion_segmento_route'),
     url(r'^qoordenes/segmentacion_rutas/coordenadas/$',
        views.segmentacion_rutas_coordenadas, name='segmentacion_rutas_coordenadas'),
     url(r'^qoordenes/segmentacion/save/$',
        views.segmentacion_save, name='segmentacion_save'),
    url(r'^qoordenes/segmentacion/asignacion/save/$',
        views.segmentacion_asignacion_save, name='segmentacion_asignacion_save'),
    url(r'^qoordenes/segmentacion/asignacion/update/$',
        views.segmentacion_asignacion_update, name='segmentacion_asignacion_update'),
    url(r'^qoordenes/segmentacion/segmentos/show/$',
        views.segmentacion_segmentos_show, name='segmentacion_segmentos_show'),
    url(r'^qoordenes/segmentacion/segmentos/edit/$',
        views.segmentacion_segmentos_edit, name='segmentacion_segmentos_edit'),
    url(r'^qoordenes/segmentacion/segmentos/delete/$',
        views.segmentacion_segmentos_delete, name='segmentacion_segmentos_delete'),
    url(r'^qoordenes/segmentacion/segmentos/update/$',
        views.segmentacion_segmentos_update, name='segmentacion_segmentos_update'),
    url(r'^qoordenes/segmentacion/areas/update/$',
        views.segmentacion_areas_show, name='segmentacion_areas_show'),
    url(r'^qoordenes/asignacion/segmento/area/delete$',
        views.asignacion_segmento_area_delete, name='asignacion_segmento_area_delete'),
    # SEGMENTACION PUNTOS DE SUMINISTROS SIN COORDENADAS
    url(r'^qoordenes/asignacion/table/puntos_sincoord/$',
        views.asignacion_table_puntos_sincoord, name='asignacion_table_puntos_sincoord'),
    url(r'^qoordenes/asignacion/ubicacion/save/$',
        views.asignacion_ubicacion_save, name='asignacion_ubicacion_save'),
   
    #ASIGNACION DE LA SEGMENTACIÓN
   url(r'^qoordenes/asignacion/attable/seg/$',
        views.asignacion_tech_seg, name='asignacion_tech_seg'),
   url(r'^qoordenes/asignacion/segmento/table$',
        views.asignacion_segmento_table, name='asignacion_segmento_table'), 
    url(r'^qoordenes/asignacion/asignaciones/seg/table$',
        views.asignacion_asignaciones_seg, name='asignacion_asignaciones_seg'),
    url(r'^qoordenes/asignacion/asignar_segmento/$',
        views.asignar_segmento, name='asignar_segmento'),
    url(r'^qoordenes/asignacion/desasignar_segmento/$',
        views.asignacion_desasignar_segmento, name='asignacion_desasignar_segmento'),
    url(r'^qoordenes/asignacion/guardar_asignar_segmentos/$',

qorder/templates/data_admin/tipo_orden/_table_tipo_ordenes.html
{% load i18n %} 
  <div class="col-md-12">
    <table id="table_tipo_ordenes" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>{% trans "Tipo" %}</th>
                                <th>{% trans "Descripción" %}</th>

                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for t in tipos_ordenes %}
                            <tr>
                                <td>{{t.tipo_orden|default_if_none:'--'}}</td>
                                <td>{{t.descripcion|default_if_none:'--'}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>


                    </table>
                    </div>
                    <script> 

          var table_tipo_ordenes = $('#table_tipo_ordenes').DataTable( {
            language: datetable_languaje,
            autoWidth: true,

            pageLength:6,

            select: 'single',
            preDrawCallback: function (settings) {
              var api = new $.fn.dataTable.Api(settings);
              var pagination = $(this)
              .closest('.dataTables_wrapper')
              .find('.dataTables_paginate');

              if (api.page.info().pages <= 1) {
                pagination.hide();
              }
              else {
                pagination.show();
              }

            }
          });

  


   table_tipo_ordenes.on( 'select', function ( e, dt, type, indexes ) {
        
        var id_to = '';
        var m_id_to= $.map(table_tipo_ordenes.rows('.selected').data(), function (item) {
            id_tp = item[0]
        });
        var filtros = {};
        filtros.csrfmiddlewaretoken = '{{csrf_token}}';
        filtros.tipo_orden=id_tp;
        $.ajax({
            url: "{% url 'qorder:tiposordenes_propiedades' %}",
            type: 'post',
            datatype: 'json',
            data: filtros,
            statusCode: {
                200: function(data) {
                
                    $("#anomalias").html(data);
                 
                },
                301: function() {
                    //Materialize.toast('El técnico no tiene asignado un dispositivo', 2000, 'red');
                },
                500: function() {
                   // Materialize.toast('Server error, contact an administrator.', 2000, 'red');
                }

            }
        });

    });






    function volver(onclick_data){
     
     //   setTimeout(function() { select_to(onclick_data); }, 100);
    }
 
                    </script>

qorder/templates/data_admin/tipo_orden/_tipos_orden.html
  {% load qorder_tags %}
  {% load i18n %} 
     <row>
    <div class="col-md-12">
        <div class="panel panel-default"  style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
            <div class="panel-heading">
                <h2 class="panel-title">
                    {% trans "tituloTipoOrdenes" %}
                </h2>
          </div>
          <div class="panel-body">
          <div id='_table_techs'>
            {% include 'data_admin/tipo_orden/_table_tipo_ordenes.html'  with feedback_form=feedback_form  %}
           </div>
           </div>
           <div class="panel-footer">

           </div>
        </div>
    </div>
     </row>   
     <div id="anomalias">      
       
     </div>